### ISSUE TITLE
dnsmasq fails to start

### ISSUE THREAD

**Issue by woodjme** [samdbmg/dhcp-netboot.xyz#11]
I'm using the following command when running the container:

```sh
docker run -d \
--net=host \
--restart=unless-stopped \
--cap-add=NET_ADMIN \
-e DHCP_RANGE_START=172.31.252.1 \
myimage-dhcp-netboot.xyz
```

On all hosts I've tried the container starts, however, on some hosts netboot's webserver starts but dnsmasq does not.
On the hosts that fail the logs look like:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
netboot.xyz: https://opencollective.com/netbootxyz/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[custom-init] No custom files found, skipping...
listening on *:3000
```

With no more output ever shown.

If this happens, I can then exec into the container and run `s6-supervise /etc/services.d/dnsmasq` and the container starts working as intended.

Any suggestions on where I can look to understand why dnsmasq isn't starting on some hosts?

*EDIT*

Something I should mention is I added 
```
# Update Nginx Port
RUN sed -i 's/80/8088/g' /defaults/default`
```

to the Dockerfile after the `FROM` as I was running into nginx already running for a different service.

**Comment by samdbmg** [comment]
Hi @woodjme, thanks for the report.

The upstream image moved to S6 v3 in https://github.com/linuxserver/docker-netbootxyz/pull/42, and in the process added a mechanism to detect when nginx becomes ready, which attempts to connect to it on port 80 (see https://github.com/linuxserver/docker-netbootxyz/blob/13722fa43491393241c275ac18ebd53d71f4199b/root/etc/s6-overlay/s6-rc.d/svc-nginx/run#L4). Changing the port means that readiness check never succeeds, which seems to block the startup of dnsmasq.

Can you try `RUN sed -i 's/80/8088/g' /defaults/default /etc/s6-overlay/s6-rc.d/svc-nginx/run` in your Dockerfile instead, and see if that works for you?

**Comment by woodjme** [comment]
Thanks @samdbmg 
This resolved my issue.
