### ISSUE TITLE
unable to access assets

### ISSUE THREAD

**Issue by zyssai** [samdbmg/dhcp-netboot.xyz#4]
Hi, first thanks, it's the only container where i'm able to boot from.
But, i'm unable to access my assets from http://192.168.0.xxx:8080
I can access them while using linuxserver/netbootxyz.

`version: '3.3'
services:
    dhcp-netboot.xyz:
        network_mode: host
        environment:
            - DHCP_RANGE_START=192.168.0.2
            - PUID=1000
            - PGID=1000
        ports:
            - '3000:3000'
            - '69:69/udp'
            - '8080:80'
        volumes:
            - '/home/username/docker/netbootxyz/config:/config'
            - '/mnt/HDD1/PXE/assets:/assets'
        restart: unless-stopped
        image: samdbmg/dhcp-netboot.xyz`

I don't know if i'm doing something wrong, or if your container just not able to mount it.
Any help appreciated

**Comment by samdbmg** [comment]
Hi, glad you found it useful! I don't think you can use port forwarding with host networking mode - in fact, when I try example with docker-compose I get:
```
Creating dhcp-netbootxyz_dhcp-netboot.xyz_1 ... 

ERROR: for dhcp-netbootxyz_dhcp-netboot.xyz_1  "host" network_mode is incompatible with port_bindings

ERROR: for dhcp-netboot.xyz  "host" network_mode is incompatible with port_bindings
```

In your case, what happens if you try and access your assets on port 80 rather than 8080? nginx should be running there I think

**Comment by zyssai** [comment]
Thanks for your answer I appreciate.
It seems to work, I can access my assets from port 80, sorry I'm not an advanced user, so didn't know this particularly with host mode.
I will try later pxe boot, and let you know.

**Comment by zyssai** [comment]
So I can see the files from web page, I attempted to boot, but unfortunately the computer is unable to load the files.

![IMG_20220310_201752](https://user-images.githubusercontent.com/15921623/157751601-8659da68-fc6f-4d3e-a4c6-69442ca16ff1.jpg)

**Comment by zyssai** [comment]
So I can see the files from web page, I attempted to boot, but unfortunately the computer is unable to load the files.

![IMG_20220310_201752](https://user-images.githubusercontent.com/15921623/157751717-88c22f7b-c39a-4b6f-93cb-527b3697bec6.jpg)
![IMG_20220310_201759](https://user-images.githubusercontent.com/15921623/157751733-28de14e4-dc9e-48cd-8cad-f00425f17e01.jpg)
![IMG_20220310_201533](https://user-images.githubusercontent.com/15921623/157751799-7ac54e89-7c9a-45b5-a68b-79c39bbac276.jpg)

**Comment by samdbmg** [comment]
What happens when it doesn't work? I've just had a go and I get to the same screen you have, press a key and then do "Load Windows Installer..." and I get this, followed by the installer starting and asking me to choose a language.
![Screenshot from 2022-03-13 15-49-00](https://user-images.githubusercontent.com/408983/158067861-ede09adc-d9c7-4652-be38-ba924cfddd1b.png)

**Comment by zyssai** [comment]
I press a key then the same screen comes again, "set the HTTP URL of an extracted ISO..."
It's strange as it worked with linuxserver/netbootxyz container.
I will make further investigations and let you know, thanks for the time you took to try.

**Comment by zyssai** [comment]
It works now, don't really know what I've done, I restarted from scratch.
Thanks again
